version: '3.9'

services:
  db:
    image: postgres
    container_name: auth-service-db
    restart: always
    ports:
      - 5432:5432 #just for Goland db client
    volumes:
      - ./build/postgres/schema.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  auth-service:
    image: auth-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_DB_USER: admin
      AUTH_SERVICE_DB_PASSWORD: admin
      AUTH_SERVICE_DB_HOST: localhost
      AUTH_SERVICE_DB_PORT: 5432
      AUTH_SERVICE_DB_NAME: postgres
      AUTH_SERVICE_DB_SERVER_PORT: 8080
    depends_on:
      - "db"
    command: ./wait-for-postgres.sh postgresql://auth-service-db/postgres?user=admin&password=admin ./auth-service

